# Generated by Django 6.0.7 on 2026-08-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bug_metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_jira_updated_cutoff', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('earliest_reliable_bucket_start', models.DateField(blank=True, null=True)),
                ('latest_reliable_bucket_end', models.DateField(blank=True, null=True)),
                ('changelog_coverage_status', models.CharField(blank=True, max_length=40)),
                ('materialized_config_version_hash', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursor', to='bug_metrics.jirascopeconfig')),
            ],
        ),
    ]
