# Generated by Django 6.0.7 on 2026-08-19 07:20

import django.db.models.deletion
import jira_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bug_metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('issue_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=120)),
                ('resolution_value', models.CharField(blank=True, max_length=120)),
                ('severity_value', models.CharField(blank=True, max_length=120)),
                ('component_value', models.CharField(blank=True, max_length=240)),
                ('owner_value', models.CharField(blank=True, max_length=240)),
                ('team_value', models.CharField(blank=True, max_length=240)),
                ('milestone_value', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_fields_json', models.JSONField(default=jira_history.models._empty_dict)),
                ('is_in_current_scope', models.BooleanField(default=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='bug_metrics.jirascopeconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'issue_key'], name='jira_histor_scope_i_0f42cf_idx'), models.Index(fields=['scope', 'is_in_current_scope'], name='jira_histor_scope_i_3d908a_idx'), models.Index(fields=['scope', 'created_at'], name='jira_histor_scope_i_68f680_idx'), models.Index(fields=['scope', 'resolved_at'], name='jira_histor_scope_i_49d52a_idx')],
                'unique_together': {('scope', 'issue_key')},
            },
        ),
        migrations.CreateModel(
            name='JiraIssueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=80)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('jira_updated_at', models.DateTimeField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(default=jira_history.models._empty_dict)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issue_snapshots', to='bug_metrics.jirascopeconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'issue_key', 'jira_updated_at'], name='jira_histor_scope_i_7c7560_idx')],
                'unique_together': {('scope', 'issue_key', 'payload_hash')},
            },
        ),
        migrations.CreateModel(
            name='JiraTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=80)),
                ('transitioned_at', models.DateTimeField()),
                ('field', models.CharField(max_length=120)),
                ('from_value', models.CharField(blank=True, max_length=240)),
                ('to_value', models.CharField(blank=True, max_length=240)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_transitions', to='bug_metrics.jirascopeconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'issue_key', 'transitioned_at'], name='jira_histor_scope_i_a9a1d1_idx'), models.Index(fields=['scope', 'field', 'to_value'], name='jira_histor_scope_i_18a060_idx')],
                'unique_together': {('scope', 'issue_key', 'transitioned_at', 'field', 'from_value', 'to_value')},
            },
        ),
    ]
