# Generated by Django 6.0.7 on 2026-08-30 09:36

import django.db.models.deletion
import provider_sync.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFactSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=80)),
                ('profile_id', models.CharField(max_length=160)),
                ('source_query_ref', models.CharField(blank=True, max_length=240)),
                ('source_query_hash', models.CharField(blank=True, max_length=64)),
                ('source_query_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('field_set_hash', models.CharField(blank=True, max_length=64)),
                ('mapping_version_hash', models.CharField(blank=True, max_length=64)),
                ('raw_payload_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('freshness_status', models.CharField(max_length=80)),
                ('status', models.CharField(default='completed', max_length=40)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider_id', 'profile_id', 'status', 'completed_at'], name='provider_sy_provide_2c17f1_idx'), models.Index(fields=['provider_id', 'profile_id', 'source_query_ref'], name='provider_sy_provide_dbe13b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=80)),
                ('profile_id', models.CharField(max_length=160)),
                ('source_item_id', models.CharField(max_length=160)),
                ('source_item_revision', models.CharField(blank=True, max_length=80)),
                ('canonical_fields_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('project_fields_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('field_values_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('provider_fields_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('mapping_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='provider_sync.providerfactsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_id', 'profile_id', 'source_item_id'], name='provider_sy_provide_b01deb_idx')],
                'unique_together': {('snapshot', 'source_item_id', 'source_item_revision')},
            },
        ),
        migrations.CreateModel(
            name='ProviderAggregateArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=80)),
                ('profile_id', models.CharField(max_length=160)),
                ('chart_id', models.CharField(max_length=120)),
                ('chart_version', models.PositiveIntegerField(default=1)),
                ('begin_ww', models.CharField(max_length=20)),
                ('end_ww', models.CharField(max_length=20)),
                ('cache_identity_hash', models.CharField(max_length=64)),
                ('freshness_status', models.CharField(max_length=80)),
                ('status', models.CharField(default='supported', max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('rows_json', models.JSONField(default=provider_sync.models._empty_list)),
                ('grafana_rows_json', models.JSONField(default=provider_sync.models._empty_list)),
                ('source_population_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('run_metadata_json', models.JSONField(default=provider_sync.models._empty_dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_artifacts', to='provider_sync.providerfactsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_id', 'profile_id', 'chart_id', 'begin_ww', 'end_ww'], name='provider_sy_provide_538b25_idx'), models.Index(fields=['cache_identity_hash'], name='provider_sy_cache_i_1695fc_idx')],
                'unique_together': {('provider_id', 'profile_id', 'chart_id', 'chart_version', 'begin_ww', 'end_ww', 'cache_identity_hash')},
            },
        ),
        migrations.CreateModel(
            name='ProviderSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=80)),
                ('profile_id', models.CharField(max_length=160)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('error_category', models.CharField(blank=True, max_length=80)),
                ('source_query_ref', models.CharField(blank=True, max_length=240)),
                ('source_query_hash', models.CharField(blank=True, max_length=64)),
                ('field_set_hash', models.CharField(blank=True, max_length=64)),
                ('mapping_version_hash', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='provider_sync.providerfactsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_id', 'profile_id', 'status'], name='provider_sy_provide_8b12d0_idx')],
                'unique_together': {('provider_id', 'profile_id')},
            },
        ),
    ]
