# Generated by Codex on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideraggregateartifact',
            name='range_end',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='provideraggregateartifact',
            name='range_grain',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='provideraggregateartifact',
            name='range_label_end',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='provideraggregateartifact',
            name='range_label_start',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='provideraggregateartifact',
            name='range_mode',
            field=models.CharField(blank=True, default='ww', max_length=20),
        ),
        migrations.AddField(
            model_name='provideraggregateartifact',
            name='range_start',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='provideraggregateartifact',
            index=models.Index(fields=['provider_id', 'profile_id', 'chart_id', 'range_mode', 'range_start', 'range_end'], name='provider_sy_provide_3db992_idx'),
        ),
    ]
