# Generated by Django 6.0.7 on 2026-08-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_sync', '0002_aggregate_range_identity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='provideraggregateartifact',
            new_name='provider_sy_provide_432707_idx',
            old_name='provider_sy_provide_3db992_idx',
        ),
    ]
