# Generated by Django 6.0.7 on 2026-08-19 07:20

import bug_metrics.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugTrendCalculationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('config_version_hash', models.CharField(max_length=64)),
                ('source_coverage_start', models.DateField()),
                ('source_coverage_end', models.DateField()),
                ('bucket_granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JiraScopeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('ip', models.CharField(blank=True, max_length=120)),
                ('project_label', models.CharField(blank=True, max_length=120)),
                ('jql', models.TextField()),
                ('bug_type_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('open_status_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('fixed_status_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('closed_status_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('terminal_excluded_status_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('fixed_resolution_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('closed_resolution_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('reopen_status_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('severity_field', models.CharField(blank=True, max_length=120)),
                ('critical_high_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('medium_low_values', models.JSONField(default=bug_metrics.models._empty_list)),
                ('component_field', models.CharField(blank=True, max_length=120)),
                ('owner_field', models.CharField(blank=True, default='assignee', max_length=120)),
                ('team_field', models.CharField(blank=True, max_length=120)),
                ('milestone_field', models.CharField(blank=True, max_length=120)),
                ('fix_version_field', models.CharField(blank=True, max_length=120)),
                ('package_version_field', models.CharField(blank=True, max_length=120)),
                ('display_fields', models.JSONField(default=bug_metrics.models._empty_list)),
                ('timezone', models.CharField(default='UTC', max_length=80)),
                ('bucket_granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('config_version_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugTrendBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_start', models.DateField()),
                ('bucket_end', models.DateField()),
                ('granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('new_critical_high_count', models.PositiveIntegerField(default=0)),
                ('new_medium_low_count', models.PositiveIntegerField(default=0)),
                ('fixed_or_closed_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('open_critical_high_count', models.PositiveIntegerField(default=0)),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='bug_metrics.bugtrendcalculationrun')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_buckets', to='bug_metrics.jirascopeconfig')),
            ],
            options={
                'ordering': ('bucket_start',),
            },
        ),
        migrations.AddField(
            model_name='bugtrendcalculationrun',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_runs', to='bug_metrics.jirascopeconfig'),
        ),
        migrations.CreateModel(
            name='BugTrendBucketIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=80)),
                ('issue_key', models.CharField(max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=120)),
                ('severity_value', models.CharField(blank=True, max_length=120)),
                ('owner_value', models.CharField(blank=True, max_length=240)),
                ('component_value', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_fields_json', models.JSONField(default=bug_metrics.models._empty_dict)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bug_metrics.bugtrendbucket')),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_issues', to='bug_metrics.bugtrendcalculationrun')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_bucket_issues', to='bug_metrics.jirascopeconfig')),
            ],
        ),
        migrations.AddIndex(
            model_name='bugtrendcalculationrun',
            index=models.Index(fields=['scope', 'status', 'config_version_hash'], name='bug_metrics_scope_i_fc9caf_idx'),
        ),
        migrations.AddIndex(
            model_name='bugtrendbucketissue',
            index=models.Index(fields=['calculation_run', 'bucket', 'series_name'], name='bug_metrics_calcula_805670_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bugtrendbucketissue',
            unique_together={('bucket', 'series_name', 'issue_key')},
        ),
        migrations.AlterUniqueTogether(
            name='bugtrendbucket',
            unique_together={('calculation_run', 'bucket_start', 'bucket_end', 'granularity')},
        ),
    ]
