# Generated by Django 6.0.7 on 2026-08-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_metrics', '0008_populate_default_chart_spec'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bugtrendauditevent',
            new_name='bug_metrics_event_t_29fd43_idx',
            old_name='bug_metrics_event_t_b83fc9_idx',
        ),
        migrations.RenameIndex(
            model_name='bugtrendchartdefinition',
            new_name='bug_metrics_enabled_ff89ae_idx',
            old_name='bug_metrics_enabled_403579_idx',
        ),
        migrations.RenameIndex(
            model_name='bugtrendrendererroutedecision',
            new_name='bug_metrics_chart_i_4a40b4_idx',
            old_name='bug_metrics_chart_i_2177f2_idx',
        ),
    ]
