# Generated by Django 6.0.7 on 2026-09-07 11:42

import bug_metrics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_metrics', '0014_provider_profile_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofileconfig',
            name='connection_settings',
            field=models.JSONField(default=bug_metrics.models._empty_dict),
        ),
    ]
