# Generated by Django 6.0.7 on 2026-09-16 15:32

import hashlib
import json
import bug_metrics.models
from django.db import migrations, models


SCOPE_SEMANTIC_LIST_FIELD_NAMES = (
    'bug_type_values',
    'open_status_values',
    'fixed_status_values',
    'closed_status_values',
    'terminal_excluded_status_values',
    'fixed_resolution_values',
    'closed_resolution_values',
    'reopen_status_values',
    'critical_high_values',
    'medium_low_values',
    'display_fields',
)


def normalize_scope_list_values(value):
    if value is None:
        return []
    if isinstance(value, str):
        raw_items = [value]
    else:
        raw_items = list(value)
    normalized = []
    for raw_item in raw_items:
        if raw_item is None:
            continue
        raw_text = str(raw_item).replace('\\r\\n', '\n').replace('\\n', '\n').replace('\\r', '\n')
        for item in raw_text.replace('\r\n', '\n').replace('\r', '\n').replace(',', '\n').split('\n'):
            text = item.strip()
            if text and text not in normalized:
                normalized.append(text)
    return normalized


def normalize_query_builder_state(value):
    if not isinstance(value, dict):
        return {}
    normalized = {}
    project = str(value.get('project') or '').strip()
    if project:
        normalized['project'] = project
    for field_name in (
        'issue_types',
        'components',
        'affected_versions',
        'fix_versions',
        'priorities',
        'resolutions',
        'security_levels',
        'labels',
    ):
        values = normalize_scope_list_values(value.get(field_name, []))
        if values:
            normalized[field_name] = values
    custom_fields = []
    for custom_field in value.get('custom_fields', []) or []:
        if not isinstance(custom_field, dict):
            continue
        field = str(custom_field.get('field') or '').strip()
        values = normalize_scope_list_values(custom_field.get('values', []))
        if field and values:
            custom_fields.append({'field': field, 'values': values})
    if custom_fields:
        normalized['custom_fields'] = custom_fields
    return normalized


def calculate_config_version_hash(scope) -> str:
    source_mode = scope.source_mode if scope.source_mode in {'custom_jql', 'query_builder'} else 'custom_jql'
    payload = {
        'source_mode': source_mode,
        'jql': scope.jql,
        'query_builder_state': normalize_query_builder_state(scope.query_builder_state) if source_mode == 'query_builder' else {},
        'bug_type_values': normalize_scope_list_values(scope.bug_type_values),
        'open_status_values': normalize_scope_list_values(scope.open_status_values),
        'fixed_status_values': normalize_scope_list_values(scope.fixed_status_values),
        'closed_status_values': normalize_scope_list_values(scope.closed_status_values),
        'terminal_excluded_status_values': normalize_scope_list_values(scope.terminal_excluded_status_values),
        'fixed_resolution_values': normalize_scope_list_values(scope.fixed_resolution_values),
        'closed_resolution_values': normalize_scope_list_values(scope.closed_resolution_values),
        'reopen_status_values': normalize_scope_list_values(scope.reopen_status_values),
        'severity_field': scope.severity_field,
        'critical_high_values': normalize_scope_list_values(scope.critical_high_values),
        'medium_low_values': normalize_scope_list_values(scope.medium_low_values),
        'component_field': scope.component_field,
        'owner_field': scope.owner_field,
        'team_field': scope.team_field,
        'milestone_field': scope.milestone_field,
        'fix_version_field': scope.fix_version_field,
        'package_version_field': scope.package_version_field,
        'display_fields': normalize_scope_list_values(scope.display_fields),
        'timezone': scope.timezone,
        'bucket_granularity': scope.bucket_granularity,
    }
    encoded_payload = json.dumps(payload, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(encoded_payload.encode('utf-8')).hexdigest()


def rehash_scope_source_modes(apps, schema_editor):
    scope_model = apps.get_model('bug_metrics', 'JiraScopeConfig')
    for scope in scope_model.objects.all():
        scope.source_mode = scope.source_mode if scope.source_mode in {'custom_jql', 'query_builder'} else 'custom_jql'
        scope.query_builder_state = normalize_query_builder_state(scope.query_builder_state)
        scope.config_version_hash = calculate_config_version_hash(scope)
        scope.save(update_fields=['source_mode', 'query_builder_state', 'config_version_hash', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('bug_metrics', '0015_providerprofileconfig_connection_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirascopeconfig',
            name='query_builder_state',
            field=models.JSONField(default=bug_metrics.models._empty_dict),
        ),
        migrations.AddField(
            model_name='jirascopeconfig',
            name='source_mode',
            field=models.CharField(choices=[('custom_jql', 'Custom JQL'), ('query_builder', 'Query Builder')], default='custom_jql', max_length=40),
        ),
        migrations.RunPython(rehash_scope_source_modes, migrations.RunPython.noop),
    ]
